app:
  container_name: "${COMPOSE_PROJECT_NAME}"
  build: .
  expose:
    - "${PHP_XDEBUG_REMOTE_PORT}"
  ports:
    - "${HOST_HTTP_PORT}:80"
    - "${HOST_HTTPS_PORT}:443"
  links:
    - mysql:${MYSQL_HOST}
    - mongo:${MONGO_HOST}
    - memcached:${MEMCACHED_HOST}
    - redis:${REDIS_HOST}
    - rabbitmq:${RABBITMQ_HOST}
  volumes:
    - ./:/var/www/html
    - ./etc/ssh:/root/.ssh
    - ./etc/nginx/sites:/etc/nginx/sites-enabled
    - ./etc/nginx/ssl:/etc/nginx/ssl
    - ./var/logs/nginx:/var/log/nginx
  env_file:
    - ./.env

mysql:
  image: mysql
  user: "1000:50"
  ports:
    - "${HOST_MYSQL_PORT}:${DB_MYSQL_PORT}"
  environment:
    MYSQL_ROOT_PASSWORD : ${DB_MYSQL_PASSWORD}
  volumes:
    -  ./var/data/mysql:/var/lib/mysql

mongo:
  image: mongo
  ports:
    - "${HOST_MONGO_PORT}:27017"
  volumes:
    - ./var/data/mongo:/data/db

memcached:
  image: memcached
  ports:
    - "${HOST_MEMCACHED_PORT}:11211"

redis:
  image: redis
  ports:
    - "HOST_REDIS_PORT:6379"

rabbitmq:
  image: rabbitmq:3.6.1-management
  ports:
    - "${HOST_RABBITMQ_ADMIN_PORT}:15672"
    - "${HOST_RABBITMQ_PORT}:5672"
